server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  application:
    name: product


# model ???? camel case ??
mybatis:
  mapper-locations: mybatis-mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# mapper ???? ??
logging:
  level:
    com:
      charminseok: debug


cloud:
  stream:
    bindings:
      productList:
        destination: product-list-topic
      teamDeleted:
        destination: team-deleted-topic
    kafka:
      binder:
        brokers: localhost:9091,localhost:9092,localhost:9093
        zkNodes: localhost:2181,localhost:2182,localhost:2183