DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT
(
    product_id   INT generated by default as identity(start with 1000000001) PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    price        INT          NOT NULL,
    stock_count  INT          NOT NULL
);
