spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa


# model 프로퍼티 camel case 설정
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.charminseok.sellerad.**.domain

# mapper 로그레벨 설정
logging:
  level:
    com:
      charminseok:
        sellerad:
          repository: TRACE