DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Company;
DROP TABLE IF EXISTS Contract;
DROP TABLE IF EXISTS Advertisement;

CREATE TABLE Product
(
    product_id   INT generated by default as identity(start with 1000000001) PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    price        INT          NOT NULL,
    stock_count  INT          NOT NULL

);

CREATE TABLE Company
(
    company_id              INT generated by default as identity(start with 1000000001) PRIMARY KEY,
    company_name            VARCHAR(255) NOT NULL,
    company_business_number INT          NOT NULL,
    company_tel             VARCHAR(15)  NOT NULL,
    company_address         VARCHAR(100) NOT NULL
);

CREATE TABLE Contract
(
    contract_id         INT generated by default as identity(start with 1000000001) PRIMARY KEY,
    company_id          INT  NOT NULL,
    contract_start_date DATE NOT NULL,
    contract_end_date   DATE NOT NULL,

    FOREIGN KEY (company_id)
        REFERENCES Company (company_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Advertisement
(
    advertisement_id    INT generated by default as identity(start with 1000000001) PRIMARY KEY,
    company_id          INT NOT NULL,
    product_id          INT NOT NULL,
    advertisement_price INT NOT NULL,

    FOREIGN KEY (company_id)
        REFERENCES Company (company_id) ON UPDATE CASCADE ON DELETE CASCADE,

    FOREIGN KEY (product_id)
        REFERENCES Product (product_id) ON UPDATE CASCADE ON DELETE CASCADE
);