DROP TABLE IF EXISTS Advertisement;

CREATE TABLE Advertisement
(
    advertisement_id    INT generated by default as identity(start with 1000000001) PRIMARY KEY,
    company_id          INT NOT NULL,
    product_id          INT NOT NULL,
    advertisement_price INT NOT NULL
);