server:
  port: 0

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:contract_db
    username: sa
  application:
    name: contract-service


mybatis:
  mapper-locations: mybatis-mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#  type-aliases-package: com.charminseok.contract.domain

# mapper ???? ??
logging:
  level:
    com:
      charminseok: debug

