DROP TABLE IF EXISTS Contract;

CREATE TABLE Contract
(
    contract_id         INT generated by default as identity(start with 1000000001) PRIMARY KEY,
    company_id          INT  NOT NULL,
    contract_start_date DATE NOT NULL,
    contract_end_date   DATE NOT NULL
);