server:
  port: 0


spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  application:
    name: company

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9091
          zkNodes: localhost:2181
      function:
        definition: productCompany;
      bindings:
        productCompany-in-0:
          destination: product-company-topic

# model ???? camel case ??
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# mapper ???? ??
logging:
  level:
    com:
      charminseok: debug

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

springdoc:
  api-docs:
    path: /openapi/${spring.application.name}