DROP TABLE IF EXISTS Company;
DROP TABLE IF EXISTS Contract;

CREATE TABLE Company
(
    company_id              INT generated by default as identity(start with 1000000001) PRIMARY KEY,
    company_name            VARCHAR(255) NOT NULL UNIQUE,
    company_business_number INT          NOT NULL,
    company_tel             VARCHAR(15)  NOT NULL,
    company_address         VARCHAR(100) NOT NULL
);

CREATE TABLE Contract
(
    contract_id         INT generated by default as identity(start with 1000000001) PRIMARY KEY,
    company_id          INT  NOT NULL,
    contract_start_date DATE NOT NULL,
    contract_end_date   DATE NOT NULL
);