DROP TABLE IF EXISTS Company;

CREATE TABLE Company
(
    company_id              INT generated by default as identity(start with 1000000001) PRIMARY KEY,
    company_name            VARCHAR(255) NOT NULL UNIQUE,
    company_business_number INT          NOT NULL,
    company_tel             VARCHAR(15)  NOT NULL,
    company_address         VARCHAR(100) NOT NULL
);